# Generated by Django 2.1.7 on 2019-02-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departName', models.CharField(max_length=200)),
                ('employees', models.ManyToManyField(to='polls.Employee')),
            ],
        ),
    ]
