# Generated by Django 2.1.7 on 2019-02-27 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='departName',
            new_name='departmentName',
        ),
    ]
