# Generated by Django 2.1.7 on 2019-02-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190226_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.AlterField(
            model_name='department',
            name='departmentName',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
