# Generated by Django 2.1.7 on 2019-02-28 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190227_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Employee', unique=True),
        ),
    ]
