# Generated by Django 2.1.7 on 2019-02-28 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190227_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Employee'),
        ),
    ]
